export const API_ENDPOINTS = {
  adminAuth: {
    login: '/auth/admin/signin',
    me: '/auth/admin/me',
    logout: '/auth/admin/signout',
    refresh: '/auth/admin/refresh',
    changePassword: '/auth/reset-password',
  },
  adminUsers: {
    list: '/admin/users',
    create: '/admin/users',
    detail: (id: string) => `/admin/users/${id}`,
    update: (id: string) => `/admin/users/${id}`,
    deactivate: (id: string) => `/admin/users/${id}/deactivate`,
    resetPassword: (id: string) => `/admin/users/${id}/reset-password`,
  },
  adminRoles: {
    permissions: '/admin/permissions',
    list: '/admin/roles',
    create: '/admin/roles',
    detail: (id: string) => `/admin/roles/${id}`,
    update: (id: string) => `/admin/roles/${id}`,
    delete: (id: string) => `/admin/roles/${id}`,
    setPermissions: (id: string) => `/admin/roles/${id}/permissions`,
  },
  adminVhs: {
    list: '/admin/vhs-submissions',
    detail: (id: string) => `/admin/vhs-submissions/${id}`,
    approve: (id: string) => `/admin/vhs-submissions/${id}/approve`,
    reject: (id: string) => `/admin/vhs-submissions/${id}/reject`,
  },
  adminSettings: {
    list: '/admin/settings',
    update: (key: string) => `/admin/settings/${key}`,
  },
  adminPayments: {
    list: '/payments/admin/list',
    overview: '/payments/admin/overview',
    activate: '/payments/admin/activate',
  },
  payments: {
    config: '/payments/config',
  },
  adminMembers: {
    overview: '/admin/members/overview',
    list: '/admin/members',
    detail: (id: string) => `/admin/members/${id}`,
    update: (id: string) => `/admin/members/${id}`,
    deactivate: (id: string) => `/admin/members/${id}/deactivate`,
  },
  forms: {
    list: '/form',
    create: '/form/create',
    detail: (id: string) => `/form/${id}`,
    detailWithCount: (id: string) => `/form/${id}/detail`,
    update: (id: string) => `/form/${id}`,
    delete: (id: string) => `/form/${id}`,
    responses: (id: string) => `/form/${id}/responses`,
    analytics: (id: string) => `/form/${id}/analytics`,
    export: (id: string) => `/form/${id}/responses/export`,
  },
  programs: {
    list: '/program',
    create: '/program/create',
    detail: (id: string) => `/program/${id}`,
    update: (id: string) => `/program/${id}`,
    delete: (id: string) => `/program/${id}`,
  },
  news: {
    list: '/news/admin/all',
    create: '/news/admin/create',
    detail: (id: string) => `/news/${id}`,
    update: (id: string) => `/news/${id}`,
    publish: (id: string) => `/news/${id}/publish`,
    unpublish: (id: string) => `/news/${id}/unpublish`,
    delete: (id: string) => `/news/${id}`,
  },
  profiles: {
    list: '/dashboard/admin/prominent-profiles',
    create: '/dashboard/admin/prominent-profiles',
    update: (id: string) => `/dashboard/admin/prominent-profiles/${id}`,
    delete: (id: string) => `/dashboard/admin/prominent-profiles/${id}`,
  },
  storage: {
    upload: '/storage/upload',
  },
  adminBranches: {
    regions: '/admin/regions',
    region: (id: string) => `/admin/regions/${id}`,
    branches: '/admin/branches',
    branch: (id: string) => `/admin/branches/${id}`,
    assignPresident: (id: string) => `/admin/branches/${id}/president`,
    progress: '/admin/analytics/progress',
    broadcast: '/admin/messages/broadcast',
  },
} as const
